FamilyBudget/Areas/Expense/Controllers/ExpenseTypesController.cs
using Expenses.App.Queries.Expense;
using FamilyBudget.Controllers.Base;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FamilyBudget.Areas.Expense.Controllers;

/// <summary>
/// Expense types controller
/// </summary>
[Area("Expense")]
[Authorize]
public class ExpenseTypesController : BaseController
{
    /// <summary>
    /// Index
    /// </summary>
    /// <returns></returns>
    public async Task<IActionResult> Index()
    {
        var data = await Mediator.Send(new GetExpenseTypesQuery());
        return View(data);
    }

    /// <summary>
    /// Create expense type
    /// </summary>
    /// <returns></returns>
    public IActionResult CreateExpenseType()
    {
        return RedirectToAction("Index");
    }

    /// <summary>
    /// Update expense type
    /// </summary>
    /// <returns></returns>
    public IActionResult UpdateExpenseType()
    {
        return RedirectToAction("Index");
    }

    /// <summary>
    /// Get expense type
    /// </summary>
    /// <returns></returns>
    public IActionResult GetExpenseTypeById()
    {
        return RedirectToAction("Index");
    }
    
    /// <summary>
    /// Delete expense type
    /// </summary>
    /// <returns></returns>
    public IActionResult DeleteExpenseType()
    {
        return RedirectToAction("Index");
    }
}

FamilyBudget/Areas/Expense/Views/ExpenseTypes/Index.cshtml
@model List<ExpenseTypeDto>

@{
    ViewBag.Title = "Создать тип расходов";
    Layout = "_Layout";
}

@await Html.PartialAsync("Partial/_CreateExpenseType", new ExpenseTypeDto())
@await Html.PartialAsync("Partial/_UpdateExpenseType", new ExpenseTypeDto())

<h3 class="text-2xl font-semibold">@ViewData["Title"]</h3>

<button id="openSidebarCreateExpenseType" class="flex items-center space-x-1">
    Create expense type
</button>

<table>
    <thead>
    <tr>
        <th>Name</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Name</td>
            <td>
                <button id="openSidebarUpdateExpenseType" onclick="GetExpenseTypeById(@item.Id)" class="flex items-center space-x-1">
                    Edit
                </button>
            </td>
        </tr>
    }
    </tbody>
</table>

@section Scripts {
    <script>
    
        $(document).ready(function () {
            AddSidebar("CreateExpenseType");
            AddSidebar("UpdateExpenseType");
        });
        
        function GetExpenseTypeById(id) {
            axios.get('@Url.Action("GetExpenseTypeById", "ExpenseTypes")', {
                params: {
                    id: id
                }
            })
            .then(function (response) {
                console.log(response);
            })
            .catch(function (error) {
                console.log(error);
            })
            .finally(function () {
                console.log("Done");
            });
        }
    
    </script>
}