FamilyBudget/Areas/Budget/Controllers/FamilyController.cs
using FamilyBudget.Controllers.Base;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FamilyBudget.Areas.Budget.Controllers;

/// <summary>
/// Family controller
/// </summary>
[Area("Budget")]
[Authorize]
public class FamilyController : BaseController
{
    /// <summary>
    /// Index
    /// </summary>
    /// <returns></returns>
    public IActionResult Index()
    {
        return View();
    }

    /// <summary>
    /// Family Budget
    /// </summary>
    /// <returns></returns>
    public IActionResult FamilyBudget()
    {
        return View();
    }

    /// <summary>
    /// Family Member Budget
    /// </summary>
    /// <returns></returns>
    public IActionResult FamilyMemberBudget()
    {
        return View();
    }

    /// <summary>
    /// Add user to family
    /// </summary>
    /// <returns></returns>
    public IActionResult AddUserToFamily()
    {
        return RedirectToAction("Index");
    }
    
    /// <summary>
    /// Remove user from family
    /// </summary>
    /// <returns></returns>
    public IActionResult RemoveUserFromFamily()
    {
        return RedirectToAction("Index");
    }
}

FamilyBudget/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - FamilyBudget</title>
    <link rel="stylesheet" href="~/css/tailwindStyles.css" />
    <script src="~/lib/axios/axios.min.js"></script>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/FamilyBudget.styles.css" asp-append-version="true"/>
</head>
<body>

    <main role="main" class="flex h-screen w-full bg-slate-50 pr-6 flex-col md:flex-row pt-4 md:pt-0">
        @await Html.PartialAsync("_Navbar")
        <div id="overlay" class="fixed inset-0 bg-black bg-opacity-50 hidden z-10"></div>
        <div id="content" class="m-6 flex w-full flex-col space-y-6 overflow-scroll rounded-md bg-white p-6">
            @RenderBody()
            <footer class="border-top footer text-muted">
                <div class="container">
                    &copy; 2023 - FamilyBudget - <a asp-area="" asp-controller="Home" asp-action="Privacy">Соглашения</a>
                </div>
            </footer>
        </div>
    </main>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

FamilyBudget/Views/Shared/_NavBar.cshtml
@using FamilyBudget.Extensions

<div class="md:hidden flex w-full justify-center">
    <button id="navbar-toggle" class="text-gray focus:outline-none">
        <svg class="h-6 w-6" viewBox="0 0 24 24" fill="none" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
        </svg>
    </button>
</div>

<nav id="navbar-menu" class="hidden md:flex flex-col h-auto md:h-full items-center space-y-3 bg-white p-3 sm:hidden md:w-4/12 xl:w-2/12">
    <a asp-area="" asp-controller="Home" asp-action="Index" class="p-3">
        <h3 class="text-blue-500 font-black text-2xl">
            FamilyBudget
        </h3>
    </a>
    <a asp-area="" asp-controller="Home" asp-action="Index" class="@Context.IsActive("/", "navBtnActive", "navBtnDefault")">
        🏠 Главная
    </a>
    <a asp-area="Budget" asp-controller="Family" asp-action="Index" class="@Context.IsActive("/Budget/Family", "navBtnActive", "navBtnDefault")">
        👪 Семья
    </a>
    <a asp-area="Expense" asp-controller="Expense" asp-action="Index" class="@Context.IsActive("/Expense/Expense", "navBtnActive", "navBtnDefault")">
        💸 Расходы
    </a>
    <a asp-area="Analyze" asp-controller="Analyze" asp-action="Index" class="@Context.IsActive("/Analyze/Analyze", "navBtnActive", "navBtnDefault")">
        💹 Аналитика
    </a>
    <a asp-area="" asp-controller="Home" asp-action="Privacy" class="@Context.IsActive("/Home/Privacy", "navBtnActive", "navBtnDefault")">
        🔥 Соглашения
    </a>
    <hr class="w-full border border-slate-50"/>
    @await Html.PartialAsync("_LoginPartial")
</nav>

@section Scripts
{
    <script>
        $(document).ready(function () {
          $("#navbar-toggle").click(function () {
            $("#navbar-menu").toggleClass("hidden");
          });
        });
    </script>
}